### ISSUE TITLE
Refactor Codable Constructors for Swift Generated Models

### ISSUE THREAD

**Issue by bsin1** [brgarciarivas/SetLife#11]
Move individual constructors out of each model class and into a static general helper function leveraging generic parameters. 

IE:  static func createModel(modelClass: codable, key: String) -> Promise<modelClass>{}

**Comment by otech47** [comment]
@bsin1 https://github.com/otech47/setlife-react-node-boilerplate/invitations

We've been using my fork since October I believe so I'll merge your commits in and we'll track issues there

https://github.com/otech47/setlife-react-node-boilerplate/issues/5

**Comment by otech47** [comment]
@bsin1 merged branch into https://github.com/otech47/setlife-react-node-boilerplate/tree/modelGenerator

Made some changes I'll reference directly in the commit one sec

**Comment by otech47** [comment]
https://github.com/otech47/setlife-react-node-boilerplate/commit/3976e5c00bc80d34e0a4b0ea3458e9d5b741fadd

Moved the swiftModel.ejs into the API folder and then changed the output location of the swift file to /models/generated. You had it in the src folder which is generally exclusive to React-related code.
